version: "3.9"

services:
  forecast_service:
    build:
      context: ./forecast_service
    ports:
      - "80:3002"
    restart: always
    networks:
      - nodejs-network

  current_weather_service:
    build:
      context: ./current_weather_service
    ports:
      - "443:3001"
    restart: always
    networks:
      - nodejs-network

networks:
  nodejs-network:
    driver: bridge
