version: "3.9"

services:
  forecastService:
    build:
      context: ./forecastService
    ports:
      - "80:3001"
    restart: always
    networks:
      - nodejs-network

  currentWeatherService:
    build:
      context: ./currentWeatherService
    ports:
      - "443:3002"
    restart: always
    networks:
      - nodejs-network

networks:
  nodejs-network:
    driver: bridge
